const data = [
  { id: 1, from: "xDai", to: "PayPal", balance: 70 },
  { id: 2, from: "xDai", to: "Venmo", balance: 500000 },
  { id: 3, from: "USDC", to: "PayPal", balance: 250 },
  { id: 4, from: "USDT", to: "Venmo", balance: 1000 },
  { id: 5, from: "xDai", to: "PayPal", balance: 790 },
  { id: 6, from: "Venmo", to: "USDT", balance: 638 },
  { id: 7, from: "PayPal", to: "Venmo", balance: 509 },
  { id: 8, from: "Venmo", to: "xDai", balance: 460 },
  { id: 9, from: "USDC", to: "Venmo", balance: 537 },
  { id: 10, from: "USDT", to: "USDC", balance: 472 },
  { id: 11, from: "PayPal", to: "USDC", balance: 730 },
  { id: 12, from: "USDT", to: "PayPal", balance: 970 },
  { id: 13, from: "USDT", to: "Venmo", balance: 564 },
  { id: 14, from: "Venmo", to: "xDai", balance: 195 },
  { id: 15, from: "USDC", to: "USDT", balance: 144 },
  { id: 16, from: "Venmo", to: "PayPal", balance: 357 },
  { id: 17, from: "xDai", to: "USDT", balance: 270 },
  { id: 18, from: "xDai", to: "Venmo", balance: 620 },
  { id: 19, from: "xDai", to: "USDT", balance: 510 },
  { id: 20, from: "PayPal", to: "USDT", balance: 639 },
  { id: 21, from: "PayPal", to: "xDai", balance: 539 },
  { id: 22, from: "USDC", to: "USDT", balance: 575 },
  { id: 23, from: "xDai", to: "Venmo", balance: 211 },
  { id: 24, from: "xDai", to: "USDC", balance: 468 },
  { id: 25, from: "PayPal", to: "Venmo", balance: 586 },
  { id: 26, from: "xDai", to: "Venmo", balance: 70 },
  { id: 27, from: "USDT", to: "xDai", balance: 196 },
  { id: 28, from: "USDC", to: "Venmo", balance: 411 },
  { id: 29, from: "USDC", to: "xDai", balance: 205 },
  { id: 30, from: "xDai", to: "PayPal", balance: 944 },
  { id: 31, from: "xDai", to: "USDC", balance: 74 },
  { id: 32, from: "PayPal", to: "xDai", balance: 584 },
  { id: 33, from: "xDai", to: "Venmo", balance: 687 },
  { id: 34, from: "USDC", to: "USDT", balance: 677 },
  { id: 35, from: "USDC", to: "PayPal", balance: 34 },
  { id: 36, from: "xDai", to: "Venmo", balance: 831 },
  { id: 37, from: "PayPal", to: "USDC", balance: 701 },
  { id: 38, from: "xDai", to: "USDC", balance: 101 },
  { id: 39, from: "xDai", to: "USDT", balance: 156 },
  { id: 40, from: "xDai", to: "Venmo", balance: 742 },
];

export default data;
